name: Contribute to Parent Repository

on:
  push:
    branches:
      - main

jobs:
  push-to-parent:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure Git
      run: |
        git config user.name "pingfan-hu"
        git config user.email "pingfan0727@gmail.com"

    - name: Push to parent repo
      run: |
        git remote add parent https://pingfan-hu:${{ secrets.PARENT_REPO_PAT }}@github.com/jhelvy/smartcharging.git
        git push parent main